// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package role_sql

import (
	"time"
)

type MasterRole struct {
	ID           int64     `json:"ID"`
	RoleCode     string    `json:"RoleCode"`
	RoleName     string    `json:"RoleName"`
	IsActive     bool      `json:"IsActive"`
	CreatedBy    int64     `json:"CreatedBy"`
	CreatedDate  time.Time `json:"CreatedDate"`
	ModifiedDate time.Time `json:"ModifiedDate"`
	ModifiedBy   int64     `json:"ModifiedBy"`
}
